spring:
  application:
    name: jute-service
  profiles:
    active: dev
server:
  port: 8101
---
 spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://35.185.136.107:3306/jute
    username: root
    password: root
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect 
---
  
## MySQL
#spring.datasource.url=jdbc:mysql://35.185.136.107:3306/jute
#spring.datasource.username=root
#spring.datasource.password=root

# drop n create table, good for testing, comment this in production
#spring.jpa.hibernate.ddl-auto=update
