spring:
  application:
    name: jute-service
  profiles:
    active: dev
server:
  port: 8101
---
 spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://35.185.136.107:3306/jute
    username: root
    password: root
  jpa:
    show-sql: true
    ddl-auto: update
    hibernate.use-new-id-generator-mappings: false
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: sakthi.dhandapani@gmail.com
    password: 2631558-pass
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false     
 amazon:
  access-key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  secret-key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  region: Testing
  s3:
   endpointUrl: XXXXXXXXXXXXXXXXXXXXXXXXXX
   bucketName: ##############################
---